[build]
builder = "dockerfile"

dockerfilePath = "Dockerfile"

[deploy]
startCommand = "./start.sh"
healthcheckPath = "/"
healthcheckTimeout = 100

[variables]
CHROMA_PERSIST_DIR = "/tmp/chroma"
APP_TYPE = "streamlit"
API_PORT = "8000"
