services:
  type: web
  name: Supply_Chain_Management_System
  env: python
  runtime: python-3.11.9
  plan: free
  buildcommands:
    - pip install -r requirements.txt
  startcommands:
    - uvicorn api.main:app --host 0.0.0.0 --port 8000